apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-vertical-pod-autoscaler
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/helm-vertical-pod-autoscaler
    meta.crossplane.io/description: Installs the Vertical Pod Autoscaler Helm chart for automatic resource right-sizing.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1.0.6"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
